import type { Metadata } from "next";
import { Bebas_Neue, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

const bebas = Bebas_Neue({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-heading",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", inter.variable, bebas.variable)}
    >
      <body className="min-h-full flex flex-col">
        <ClerkProvider>
          <Navbar />
          <main className="flex-1">{children}</main>
          <footer className="">
            <div className="container mx-auto px-4 text-center text">
              <p className="">made with love by Drew</p>
            </div>
          </footer>
        </ClerkProvider>
      </body>
    </html>
  );
}
