// import type { Metadata } from "next";
// import { Bebas_Neue, Inter } from "next/font/google";
// import "../globals.css";
// import { cn } from "@/lib/utils";
// import Navbar from "@/components/Navbar";
// import { ClerkProvider } from "@clerk/nextjs";
// import { TooltipProvider } from "@/components/ui/tooltip";

// const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

// const bebas = Bebas_Neue({
//   weight: "400",
//   subsets: ["latin"],
//   variable: "--font-heading",
// });
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={cn("h-full", "antialiased", inter.variable, bebas.variable)}
//     >
//       <body className="min-h-full flex flex-col">
//         <ClerkProvider>
//           <Navbar />
//           <main className="flex-1">
//             {" "}
//             <TooltipProvider>{children}</TooltipProvider>
//           </main>
//           <footer className="">
//             <div className="container mx-auto px-4 text-center text">
//               <p className="">made with love by Drew</p>
//             </div>
//           </footer>
//         </ClerkProvider>
//       </body>
//     </html>
//   );
// }
import type { Metadata } from "next";
import { TooltipProvider } from "@/components/ui/tooltip";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "law firm",
  description: "find a lawyer online.",
};

export default function MainLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <TooltipProvider>
      <Navbar />
      <main className="flex-1">{children}</main>
      <footer>
        <div className="container mx-auto px-4 text-center">
          <p>made with love by Drew</p>
        </div>
      </footer>
    </TooltipProvider>
  );
}
